# Generated by Django 2.2.2 on 2019-07-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctrs_texts', '0003_auto_20190719_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractedtext',
            name='encoded_texts',
        ),
        migrations.AddField(
            model_name='encodedtext',
            name='abstracted_text',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='encoded_texts', to='ctrs_texts.AbstractedText'),
            preserve_default=False,
        ),
    ]
