# Generated by Django 2.2.7 on 2020-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrs_texts', '0005_auto_20190731_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractedtext',
            options={'ordering': ['short_name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='abstractedtexttype',
            options={'ordering': ['short_name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='encodedtexttype',
            options={'ordering': ['short_name', 'name']},
        ),
        migrations.AddField(
            model_name='abstractedtext',
            name='imported_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encodedtext',
            name='imported_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='imported_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='imported_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
