# Generated by Django 2.2.7 on 2020-01-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctrs_texts', '0006_auto_20200118_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractedtext',
            name='manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscript_texts', to='ctrs_texts.Manuscript'),
        ),
        migrations.DeleteModel(
            name='ManuscriptText',
        ),
    ]
