# Generated by Django 2.2.7 on 2020-01-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrs_texts', '0007_auto_20200118_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractedtext',
            name='locus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
