# Generated by Django 2.2.12 on 2020-04-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrs_texts', '0010_load_encodedtext_plain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodedtext',
            name='plain',
            field=models.TextField(blank=True, help_text='Content in plain text', null=True),
        ),
    ]
