# Generated by Django 2.2.7 on 2019-12-05 15:19

from django.conf import settings
from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_blogpost_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='authored_blogposts', to=settings.AUTH_USER_MODEL, verbose_name='authors'),
        ),
    ]
