# Generated by Django 2.2.10 on 2020-03-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20200313_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='show_in_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_in_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_in_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='show_in_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peopleindexpage',
            name='show_in_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='show_in_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='richtextpage',
            name='show_in_main_menu',
            field=models.BooleanField(default=False),
        ),
    ]
