# Generated by Django 2.2.2 on 2019-07-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctrs_texts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscripttext',
            old_name='short_name',
            new_name='locus',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='manuscripttext',
            name='created',
        ),
        migrations.RemoveField(
            model_name='manuscripttext',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='manuscripttext',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manuscripttext',
            name='slug',
        ),
        migrations.AlterField(
            model_name='abstractedtext',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ctrs_texts.AbstractedText'),
        ),
        migrations.AlterField(
            model_name='abstractedtext',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abstracted_texts', to='ctrs_texts.AbstractedTextType'),
        ),
        migrations.AlterField(
            model_name='encodedtext',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_texts', to='ctrs_texts.EncodedTextStatus'),
        ),
        migrations.AlterField(
            model_name='encodedtext',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_texts', to='ctrs_texts.EncodedTextType'),
        ),
        migrations.AlterField(
            model_name='manuscripttext',
            name='manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscript_texts', to='ctrs_texts.Manuscript'),
        ),
    ]
