# Generated by Django 2.2.2 on 2019-07-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrs_texts', '0002_auto_20190719_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
    ]
