# Generated by Django 2.2.3 on 2019-07-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrs_texts', '0004_auto_20190720_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractedtext',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='abstractedtexttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='encodedtexttype',
            options={'ordering': ['name']},
        ),
    ]
